import { Project, ServiceItem, Testimonial, FAQItem, SiteSettings, Enquiry } from '@/types';

export const initialSiteSettings: SiteSettings = {
  company_name: "MK CONSTRUCTION",
  location: "THIRUBUVANAM, TAMIL NADU",
  established_year: 2000,
  owner_mobile: "+919150786656",
  owner_email: "sathishsathish979139@gmail.com",
  address: "38/4 , Kalaigar Nagar ,Thirubuvanam, 612103",
  working_hours: "Mon to Sat, 9 am to 6 pm",
  hero_title: "Master Craftsmanship. Solid Foundations Since 2000.",
  hero_subtitle: "Building iconic dream homes, high-yield commercial complexes, and bespoke interiors across Thirubuvanam, Kumbakonam, and Tamil Nadu with uncompromised engineering precision.",
  stats_projects_count: "250+",
  stats_years_experience: "26+",
  stats_happy_clients: "380+",
  stats_warranty_years: "10 Years",
  whatsapp_enquiry_number: "+919150786656",
  notification_channels: {
    whatsapp: true,
    sms: true,
    email: true,
  },
  license_number: "[TN-PWD-CLASS-1-REG-2000]",
  insurance_status: "[₹5 Crore Comprehensive Builder's Risk & Public Liability Insured]",
  safety_standard: "[IS 456:2000 Concrete Compliance & Zero-Accident Site Protocol]",
};

export const initialServices: ServiceItem[] = [
  {
    id: "service-1",
    title: "New Home Construction",
    slug: "new-home-construction",
    icon_name: "Home",
    short_desc: "Custom turnkey luxury villas, contemporary duplexes, and traditional Chettinad-style residences built to endure generations.",
    full_desc: "From soil testing and structural RCC design to premium finishes, we deliver complete turnkey homes tailored to your lifestyle, climate, and Vastu requirements.",
    features: [
      "Soil bearing capacity testing & seismic structural design",
      "Grade-43/53 high-tensile TMT steel & Ultratech/Ramco cement",
      "Vastu-compliant architectural floor planning",
      "10-year comprehensive structural warranty",
      "Live milestone tracking with photo updates for owners"
    ],
    display_order: 1,
    is_active: true,
  },
  {
    id: "service-2",
    title: "Commercial Buildings",
    slug: "commercial-buildings",
    icon_name: "Building2",
    short_desc: "State-of-the-art retail complexes, office spaces, warehouses, and institutional buildings built for maximum ROI and safety.",
    full_desc: "We construct commercial facilities engineered for high footfall, energy efficiency, flexible floor layouts, and strict regulatory compliance.",
    features: [
      "Pre-engineered steel and post-tensioned slab options",
      "Heavy load bearing floors & heavy-duty industrial finishes",
      "Integrated fire fighting, MEP, and HVAC shaft provisions",
      "On-time project delivery with contractual penalty protection",
      "Local municipal approval (DTCP/CMDA) documentation assistance"
    ],
    display_order: 2,
    is_active: true,
  },
  {
    id: "service-3",
    title: "Renovation & Remodeling",
    slug: "renovation-remodeling",
    icon_name: "Wrench",
    short_desc: "Transform aged structures into modern, energy-efficient masterpieces with structural retrofitting and aesthetic elevations.",
    full_desc: "Specialized in structural retrofitting, vertical expansions, waterproofing, roof slab restoration, and contemporary exterior facelift.",
    features: [
      "Non-destructive structural integrity audit",
      "Carbon fiber wrapping & micro-concrete column jacketing",
      "Advanced chemical polymer waterproofing membranes",
      "Complete exterior facade modernization with ACP/Texture",
      "Minimal disturbance to adjacent buildings"
    ],
    display_order: 3,
    is_active: true,
  },
  {
    id: "service-4",
    title: "Interiors & Architecture",
    slug: "interiors-architecture",
    icon_name: "Palette",
    short_desc: "End-to-end bespoke interior design, modular kitchen crafting, false ceilings, and ambient architectural lighting.",
    full_desc: "Harmonizing functional utility with bespoke aesthetics. We design modular kitchens, teak wood wardrobes, acoustic false ceilings, and premium flooring.",
    features: [
      "3D photorealistic architectural renders & walkthroughs",
      "Marine grade 710 BWP plywood & German Blum/Hafele hardware",
      "Custom Italian marble, granites, and vitrified tile laying",
      "Automated smart ambient lighting & acoustic ceiling designs",
      "Factory finish edge-banding and precision woodwork"
    ],
    display_order: 4,
    is_active: true,
  }
];

export const initialProjects: Project[] = [
  {
    id: "proj-1",
    title: "The Rajan Royal Residence",
    slug: "rajan-royal-residence",
    project_type: "Residential",
    area_sqft: 3850,
    duration: "11 Months",
    location: "Kalaigar Nagar, Thirubuvanam",
    budget_range: "₹85 - 95 Lakhs",
    description: "A majestic 4-BHK contemporary residence incorporating passive cooling ventilation, double-height living foyer, handcrafted teak woodwork, and a rooftop solar terrace garden.",
    is_featured: true,
    is_published: true,
    display_order: 1,
    created_at: "2025-11-15T10:00:00Z",
    photos: [
      {
        id: "photo-1-1",
        project_id: "proj-1",
        storage_path: "projects/rajan-residence/facade.jpg",
        public_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
        caption: "Front elevation featuring warm timber louvers and floating balcony cantilever",
        is_cover: true,
        photo_tag: "after",
        display_order: 1,
        created_at: "2025-11-15T10:00:00Z",
      },
      {
        id: "photo-1-2",
        project_id: "proj-1",
        storage_path: "projects/rajan-residence/site-before.jpg",
        public_url: "https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?auto=format&fit=crop&w=1200&q=80",
        caption: "Original uneven agricultural plot prior to excavation and PCC footing",
        is_cover: false,
        photo_tag: "before",
        display_order: 2,
        created_at: "2025-11-15T10:00:00Z",
      },
      {
        id: "photo-1-3",
        project_id: "proj-1",
        storage_path: "projects/rajan-residence/living.jpg",
        public_url: "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1200&q=80",
        caption: "Double-height living space with imported Italian marble and warm cove illumination",
        is_cover: false,
        photo_tag: "standard",
        display_order: 3,
        created_at: "2025-11-15T10:00:00Z",
      },
      {
        id: "photo-1-4",
        project_id: "proj-1",
        storage_path: "projects/rajan-residence/kitchen.jpg",
        public_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80",
        caption: "High-gloss acrylic modular kitchen with quartz countertop and built-in appliances",
        is_cover: false,
        photo_tag: "standard",
        display_order: 4,
        created_at: "2025-11-15T10:00:00Z",
      },
    ],
  },
  {
    id: "proj-2",
    title: "Thirubuvanam Silk & Retail Hub",
    slug: "thirubuvanam-silk-retail-hub",
    project_type: "Commercial",
    area_sqft: 8500,
    duration: "14 Months",
    location: "Main Road, Thirubuvanam",
    budget_range: "₹2.2 - 2.5 Crore",
    description: "G+3 commercial retail complex engineered with wide column spans, floor-to-ceiling glass curtain facade, dual high-speed elevators, and centralized fire sprinkler system.",
    is_featured: true,
    is_published: true,
    display_order: 2,
    created_at: "2025-08-20T10:00:00Z",
    photos: [
      {
        id: "photo-2-1",
        project_id: "proj-2",
        storage_path: "projects/commercial-hub/exterior.jpg",
        public_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
        caption: "Modern glass curtain wall commercial facade on Thirubuvanam arterial highway",
        is_cover: true,
        photo_tag: "after",
        display_order: 1,
        created_at: "2025-08-20T10:00:00Z",
      },
      {
        id: "photo-2-2",
        project_id: "proj-2",
        storage_path: "projects/commercial-hub/excavation-before.jpg",
        public_url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80",
        caption: "Deep foundation piling and earth retention before basement RCC pour",
        is_cover: false,
        photo_tag: "before",
        display_order: 2,
        created_at: "2025-08-20T10:00:00Z",
      },
      {
        id: "photo-2-3",
        project_id: "proj-2",
        storage_path: "projects/commercial-hub/showroom.jpg",
        public_url: "https://images.unsplash.com/photo-1582037928769-181f2644ecb7?auto=format&fit=crop&w=1200&q=80",
        caption: "Column-free grand retail showroom level with heavy duty vitrified floor tiles",
        is_cover: false,
        photo_tag: "standard",
        display_order: 3,
        created_at: "2025-08-20T10:00:00Z",
      },
    ],
  },
  {
    id: "proj-3",
    title: "Heritage Chettiar Villa Facelift",
    slug: "heritage-chettiar-villa-facelift",
    project_type: "Renovation",
    area_sqft: 2900,
    duration: "6 Months",
    location: "Kumbakonam Road, Thirubuvanam",
    budget_range: "₹45 - 55 Lakhs",
    description: "Complete structural strengthening and modernization of a 40-year-old home. Replaced crumbling Madras terrace with lightweight RCC, waterproofed foundations, and integrated modern amenities while preserving wooden heritage pillars.",
    is_featured: true,
    is_published: true,
    display_order: 3,
    created_at: "2025-06-10T10:00:00Z",
    photos: [
      {
        id: "photo-3-1",
        project_id: "proj-3",
        storage_path: "projects/heritage-reno/after.jpg",
        public_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        caption: "Post-renovation exterior: vibrant terracotta tones, weatherproof coating, and refreshed portico",
        is_cover: true,
        photo_tag: "after",
        display_order: 1,
        created_at: "2025-06-10T10:00:00Z",
      },
      {
        id: "photo-3-2",
        project_id: "proj-3",
        storage_path: "projects/heritage-reno/before.jpg",
        public_url: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1200&q=80",
        caption: "Pre-renovation: cracked plaster, roof seepages, and severely weathered exterior",
        is_cover: false,
        photo_tag: "before",
        display_order: 2,
        created_at: "2025-06-10T10:00:00Z",
      },
    ],
  },
  {
    id: "proj-4",
    title: "Lotus Luxury Penthouse Interiors",
    slug: "lotus-luxury-penthouse-interiors",
    project_type: "Interiors",
    area_sqft: 2150,
    duration: "4 Months",
    location: "Cauvery Riverside, Thirubuvanam",
    budget_range: "₹30 - 38 Lakhs",
    description: "Turnkey architectural interior styling featuring veneer wall panels, acoustic home theatre ceiling, custom fluted glass partitions, and ergonomic workspace cabinetry.",
    is_featured: false,
    is_published: true,
    display_order: 4,
    created_at: "2025-04-01T10:00:00Z",
    photos: [
      {
        id: "photo-4-1",
        project_id: "proj-4",
        storage_path: "projects/penthouse/living.jpg",
        public_url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
        caption: "Custom veneer media console with indirect gold LED backlighting",
        is_cover: true,
        photo_tag: "standard",
        display_order: 1,
        created_at: "2025-04-01T10:00:00Z",
      },
      {
        id: "photo-4-2",
        project_id: "proj-4",
        storage_path: "projects/penthouse/bedroom.jpg",
        public_url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80",
        caption: "Master suite with bespoke padded headboard and integrated acoustic wood paneling",
        is_cover: false,
        photo_tag: "standard",
        display_order: 2,
        created_at: "2025-04-01T10:00:00Z",
      }
    ],
  }
];

export const initialTestimonials: Testimonial[] = [
  {
    id: "test-1",
    client_name: "[K. Saravanan]",
    client_role: "Silk Merchant & Villa Owner",
    location: "Thirubuvanam, Tamil Nadu",
    rating: 5,
    comment: "MK Construction built our 3,850 sq.ft dream villa in Kalaigar Nagar. Their transparency in material billing, daily progress photos on WhatsApp, and on-time completion within 11 months won our complete trust. 100% recommended!",
    project_title: "The Rajan Royal Residence",
    display_order: 1,
    is_featured: true,
  },
  {
    id: "test-2",
    client_name: "[Dr. M. Senthil Kumar]",
    client_role: "Hospital Director",
    location: "Kumbakonam, Tamil Nadu",
    rating: 5,
    comment: "For our commercial retail complex, Sathish and the MK Construction engineering crew adhered strictly to structural seismic codes and zero safety compromises. Even during monsoon downpours, work progressed like clockwork.",
    project_title: "Thirubuvanam Silk & Retail Hub",
    display_order: 2,
    is_featured: true,
  },
  {
    id: "test-3",
    client_name: "[R. Meenakshi Sundaram]",
    client_role: "Retired Bank Officer",
    location: "Thanjavur, Tamil Nadu",
    rating: 5,
    comment: "Our 40-year old ancestral home had deep dampness and sagging roof beams. MK Construction carried out retrofitting and aesthetic remodeling that gave our home a brand new life for another 50 years without losing heritage charm.",
    project_title: "Heritage Chettiar Villa Facelift",
    display_order: 3,
    is_featured: true,
  }
];

export const initialFAQs: FAQItem[] = [
  {
    id: "faq-1",
    question: "What is your construction cost per square foot in Thirubuvanam & Tamil Nadu?",
    answer: "Our standard turnkey residential construction rates range from ₹1,850 to ₹2,600 per sq.ft depending on finishes, structural soil conditions, and architectural complexity. Premium luxury specifications with imported marble and teak woodwork range from ₹2,800 to ₹3,500 per sq.ft. We give you an itemized line-by-line BOQ (Bill of Quantities) with zero hidden surprises.",
    category: "Cost & Estimation",
    display_order: 1,
    is_published: true,
  },
  {
    id: "faq-2",
    question: "Do you handle local municipal planning approvals and DTCP sanctioning?",
    answer: "Yes! As licensed Class-1 contractors established since 2000, we manage end-to-end architectural blue-printing, structural design certificates, soil test submissions, and local Panchayat/DTCP/Corporation plan approvals on behalf of our clients.",
    category: "Approvals & Licensing",
    display_order: 2,
    is_published: true,
  },
  {
    id: "faq-3",
    question: "How do I monitor construction progress if I live out-of-town or abroad (NRI)?",
    answer: "We provide complete transparency! Every week, you receive high-resolution drone and site photos, video walkthroughs, and detailed milestone status reports via WhatsApp and email. You also have direct access to the project lead.",
    category: "Project Management",
    display_order: 3,
    is_published: true,
  },
  {
    id: "faq-4",
    question: "What structural warranty and water-leakage guarantees do you provide?",
    answer: "All MK Construction new buildings carry a written 10-Year Structural RCC Warranty and a 5-Year Comprehensive Waterproofing Guarantee for all roof slabs, sunken slabs, and basements.",
    category: "Warranty & Quality",
    display_order: 4,
    is_published: true,
  },
  {
    id: "faq-5",
    question: "What payment schedule do you follow for construction contracts?",
    answer: "We follow a strictly milestone-linked payment structure: Token advance (10%), Plinth beam completion (15%), Ground floor roof pour (20%), First floor roof pour (20%), Brickwork & plastering (15%), Flooring & painting (15%), and Handover balance (5%). You only pay as tangible construction milestones are inspected and verified.",
    category: "Payment Terms",
    display_order: 5,
    is_published: true,
  }
];

export const initialEnquiries: Enquiry[] = [
  {
    id: "enq-101",
    name: "Arunachalam Murugesan",
    mobile: "9842145890",
    location: "Thirubuvanam East",
    project_type: "Residential",
    budget: "₹35 - ₹75 Lakhs",
    message: "Looking to build a 2-storey independent villa on a 2400 sq.ft plot. Need Vastu plan and initial elevation concept.",
    consent: true,
    status: "New",
    owner_notes: "Followed up via phone on Oct 3. Client wants to schedule site visit this Saturday morning.",
    ip_hash: "103.21.244.12",
    created_at: "2026-10-02T16:45:00Z",
    updated_at: "2026-10-03T09:30:00Z",
  },
  {
    id: "enq-102",
    name: "Dr. Kavitha Sundaram",
    mobile: "9443217894",
    location: "Kumbakonam City",
    project_type: "Commercial",
    budget: "₹75 Lakhs - ₹1.5 Cr",
    message: "Constructing a dental clinic and 3 rental commercial retail shops on main road.",
    consent: true,
    status: "Quote sent",
    owner_notes: "Detailed structural BOQ sent on email. Client reviewing with architect.",
    ip_hash: "157.48.91.44",
    created_at: "2026-09-28T11:15:00Z",
    updated_at: "2026-09-30T14:20:00Z",
  },
  {
    id: "enq-103",
    name: "V. Balasubramanian",
    mobile: "9789456123",
    location: "Thanjavur Highway",
    project_type: "Renovation",
    budget: "₹15 - ₹35 Lakhs",
    message: "Roof waterproofing and elevation facelift needed for 25-year-old house.",
    consent: true,
    status: "Contacted",
    owner_notes: "Visited site on Sep 25. Recommended polymer coating and micro-concrete strengthening.",
    ip_hash: "49.37.199.88",
    created_at: "2026-09-24T08:50:00Z",
    updated_at: "2026-09-25T18:00:00Z",
  },
  {
    id: "enq-104",
    name: "G. Rajesh Kannan",
    mobile: "9150123456",
    location: "Thirubuvanam Weavers Colony",
    project_type: "Residential",
    budget: "₹35 - ₹75 Lakhs",
    message: "Turnkey duplex home construction. Need quote for G+1 2200 sq.ft building.",
    consent: true,
    status: "Won",
    owner_notes: "Contract signed on Sep 20! Soil testing scheduled for next Monday.",
    ip_hash: "117.200.45.10",
    created_at: "2026-09-18T14:10:00Z",
    updated_at: "2026-09-20T17:30:00Z",
  }
];
